-- CREAZIONE DELLE RELAZIONI --
-- Creazione Tabella ATTIVITA_COMMERCIALI
CREATE TABLE ATTIVITA_COMMERCIALI (
ID_Attivita VARCHAR2(30),
Nome VARCHAR2(100) NOT NULL, 
Valutazione_Media NUMBER DEFAULT 0, 
Indirizzo VARCHAR2(150),
Città VARCHAR2(50)NOT NULL,
CAP VARCHAR2(50),
Stato VARCHAR2(10),
Latitudine NUMBER,
Longitudine NUMBER,
Num_Recensioni INTEGER DEFAULT 0,
CONSTRAINT PK_ID_Attivita PRIMARY KEY (ID_Attivita),
CONSTRAINT Check_Valutazione_Media CHECK (Valutazione_Media >= 0 AND Valutazione_Media <= 5)
);

-- Creazione Tabella CATEGORIE
CREATE TABLE CATEGORIE (
ID_Categoria VARCHAR2(50),
CONSTRAINT PK_ID_Categoria PRIMARY KEY (ID_Categoria)
);

-- Creazione Tabella SERVIZI
CREATE TABLE SERVIZI (
ID_Servizio VARCHAR2(50),
CONSTRAINT PK_ID_Servizio PRIMARY KEY (ID_Servizio)
);

-- Creazione Tabella APPARTENENZE_CATEGORIE
CREATE TABLE APPARTENENZE_CATEGORIE(
Attivita VARCHAR2(30),
Categoria VARCHAR2(50),
CONSTRAINT PK_Appartenza_Categoria PRIMARY KEY(Attivita, Categoria)
);

-- Creazione Tabella OFFERTE_SERVIZI
CREATE TABLE OFFERTE_SERVIZI(
Servizio VARCHAR2(30),
Attivita VARCHAR2(50),
CONSTRAINT PK_Offerta_Servizio PRIMARY KEY(Servizio, Attivita)
);

-- Creazione Tabella CHECK_IN
CREATE TABLE CHECK_IN(
Data TIMESTAMP,
Attivita VARCHAR2(30),
CONSTRAINT PK_Check_In PRIMARY KEY (Data, Attivita)
);

-- Creazione Tabella ORARI_LAVORATIVI
CREATE TABLE ORARI_LAVORATIVI(
Giorno VARCHAR2(30),
Attivita VARCHAR2(30),
Orario_Apertura VARCHAR2(5), 
Orario_Chiusura VARCHAR2(5), 
CONSTRAINT PK_Orario_Lavorativo PRIMARY KEY (Giorno, Attivita)
);

-- Creazione Tabella FOTOGRAFIE
CREATE TABLE FOTOGRAFIE(
ID_Fotografia VARCHAR2(30),
Testo CLOB,
Immagine BLOB,
Etichetta VARCHAR2(50),
Attivita VARCHAR2(30) NOT NULL,
Utente VARCHAR2(30), --Puo’ essere NULL
CONSTRAINT PK_ID_Fotografia PRIMARY KEY (ID_Fotografia)
);

-- Creazione Tabella UTENTI
CREATE TABLE UTENTI(
ID_Utente VARCHAR2(30),
Nome VARCHAR2(50) NOT NULL,
Data_Iscrizione DATE DEFAULT SYSDATE,
Num_Recensioni INTEGER DEFAULT 0,
Num_Complimenti_Cool INTEGER DEFAULT 0, 
Num_Complimenti_Funny INTEGER DEFAULT 0,
Num_Complimenti_Useful INTEGER DEFAULT 0, 
Valutazione_Media_Recensioni NUMBER DEFAULT 0,
CONSTRAINT Check_Valutazione_Media_Recensioni CHECK (Valutazione_Media_Recensioni >= 0 AND Valutazione_Media_Recensioni <= 5),
CONSTRAINT PK_ID_Utente PRIMARY KEY (ID_Utente)
);

-- Creazione Tabella AMICIZIE
CREATE TABLE AMICIZIE(
Utente VARCHAR2(30),
Amico VARCHAR2(30),
CONSTRAINT PK_Amicizia PRIMARY KEY(Utente, Amico)
);

-- Creazione Tabella RECENSIONI
CREATE TABLE RECENSIONI(
ID_Recensione VARCHAR2(30),
Data TIMESTAMP DEFAULT SYSDATE,
Testo CLOB,
Valutazione INTEGER NOT NULL,
Num_Valutazioni_Divertenti INTEGER DEFAULT 0, 
Num_Valutazioni_Interessanti INTEGER DEFAULT 0,
Num_Valutazioni_Utili INTEGER DEFAULT 0, 
Attivita VARCHAR2(30) NOT NULL,
Utente VARCHAR2(30) NOT NULL,
CONSTRAINT PK_ID_Recensione PRIMARY KEY (ID_Recensione),
CONSTRAINT Check_Valutazione CHECK (Valutazione >= 0 AND Valutazione <= 5)
);

-- Creazione Tabella SUGGERIMENTI
CREATE TABLE SUGGERIMENTI(
Data DATE,
Utente VARCHAR2(30),
Attivita VARCHAR2(30),
Testo CLOB NOT NULL,
Num_Complimenti INTEGER DEFAULT 0, 
CONSTRAINT PK_Suggerimento PRIMARY KEY (Data, Utente, Attivita)
);

-- VINCOLI D'INTREGITA' REFERENZIALE --
-- Definizione delle Foreign Key per la tabella FOTOGRAFIE 
ALTER TABLE FOTOGRAFIE ADD CONSTRAINT FK_FOTOGRAFIE_ATTIVITA 
FOREIGN KEY(Attivita) REFERENCES ATTIVITA_COMMERCIALI(ID_Attivita)
ON DELETE CASCADE;

ALTER TABLE FOTOGRAFIE ADD CONSTRAINT FK_FOTOGRAFIE_UTENTI 
FOREIGN KEY(Utente) REFERENCES UTENTI(ID_Utente)
ON DELETE CASCADE;

-- Definizione delle Foreign Key per la tabella RECENSIONI 
ALTER TABLE RECENSIONI ADD CONSTRAINT FK_RECENSIONI_ATTIVITA 
FOREIGN KEY(Attivita) REFERENCES ATTIVITA_COMMERCIALI(ID_Attivita)
ON DELETE CASCADE;

ALTER TABLE RECENSIONI ADD CONSTRAINT FK_RECENSIONI_UTENTI 
FOREIGN KEY(Utente) REFERENCES UTENTI(ID_Utente)
ON DELETE CASCADE;

-- Definizione delle Foreign Key per la tabella CHECK_IN
ALTER TABLE CHECK_IN ADD CONSTRAINT FK_CHECKIN_ATTIVITA 
FOREIGN KEY(Attivita) REFERENCES ATTIVITA_COMMERCIALI(ID_Attivita)
ON DELETE CASCADE;

-- Definizione delle Foreign Key per la tabella ORARI_LAVORATIVI 
ALTER TABLE ORARI_LAVORATIVI ADD CONSTRAINT FK_ORARI_ATTIVITA 
FOREIGN KEY(Attivita) REFERENCES ATTIVITA_COMMERCIALI(ID_Attivita)
ON DELETE CASCADE;

-- Definizione delle Foreign Key per la tabella SUGGERIMENTI
ALTER TABLE SUGGERIMENTI ADD CONSTRAINT FK_SUGGERIMENTI_ATTIVITA 
FOREIGN KEY(Attivita) REFERENCES ATTIVITA_COMMERCIALI(ID_Attivita)
ON DELETE CASCADE;

ALTER TABLE SUGGERIMENTI ADD CONSTRAINT FK_SUGGERIMENTI_UTENTI 
FOREIGN KEY(Utente) REFERENCES UTENTI(ID_Utente)
ON DELETE CASCADE;

-- Definizione delle Foreign Key per la tabella  APPARTENENZE_CATEGORIE
ALTER TABLE APPARTENENZE_CATEGORIE ADD CONSTRAINT FK_APP_ATTIVITA 
FOREIGN KEY(Attivita) REFERENCES ATTIVITA_COMMERCIALI(ID_Attivita)
ON DELETE CASCADE;

ALTER TABLE APPARTENENZE_CATEGORIE ADD CONSTRAINT FK_APP_CATEGORIE
FOREIGN KEY(Categoria) REFERENCES CATEGORIE(ID_Categoria)
ON DELETE CASCADE;

-- Definizione delle Foreign Key per la tabella OFFERTE_SERVIZI
ALTER TABLE OFFERTE_SERVIZI ADD CONSTRAINT FK_OFFERTE_ATTIVITA 
FOREIGN KEY(Attivita) REFERENCES ATTIVITA_COMMERCIALI(ID_Attivita)
ON DELETE CASCADE;

-- Definizione delle Foreign Key per la tabella AMICIZIE
ALTER TABLE AMICIZIE ADD CONSTRAINT FK_AMICIZIE_UTENTI 
FOREIGN KEY(Utente) REFERENCES UTENTI(ID_Utente)
ON DELETE CASCADE;

-- CREAZIONE DEI RUOLI E DEGLI UTENTI --
-- Definizione del ruolo ADMIN (Gestione completa del sistema)
CREATE ROLE RUOLO_ADMIN;

-- Definizione del ruolo MODERATOR (Gestione contenuti degli utenti)
CREATE ROLE RUOLO_MODERATOR;

-- Definizione del ruolo USER (Gestione dei propri)
CREATE ROLE RUOLO_USER;

-- L’ADMIN può gestire in maniera completa tutto il sistema.
-- Concediamo a tale ruolo privilegi completi su tutte le tabelle
GRANT ALL PRIVILEGES ON ATTIVITA_COMMERCIALI TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON CATEGORIE TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON SERVIZI TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON FOTOGRAFIE TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON UTENTI TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON RECENSIONI TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON CHECK_IN TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON ORARI_LAVORATIVI TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON SUGGERIMENTI TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON APPARTENENZE_CATEGORIE TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON OFFERTE_SERVIZI TO RUOLO_ADMIN;
GRANT ALL PRIVILEGES ON AMICIZIE TO RUOLO_ADMIN;

-- Il MODERATOR può gestire soltanto i contenuti di altri utenti.
-- Concediamo a tale ruolo il privilegio di SELEZIONE su tutte le tabelle della base di dati
GRANT SELECT ON ATTIVITA_COMMERCIALI TO RUOLO_MODERATOR;
GRANT SELECT ON CATEGORIE TO RUOLO_MODERATOR;
GRANT SELECT ON SERVIZI TO RUOLO_MODERATOR;
GRANT SELECT ON FOTOGRAFIE TO RUOLO_MODERATOR;
GRANT SELECT ON UTENTI TO RUOLO_MODERATOR;
GRANT SELECT ON RECENSIONI TO RUOLO_MODERATOR;
GRANT SELECT ON CHECK_IN TO RUOLO_MODERATOR;
GRANT SELECT ON ORARI_LAVORATIVI TO RUOLO_MODERATOR;
GRANT SELECT ON SUGGERIMENTI TO RUOLO_MODERATOR;
GRANT SELECT ON APPARTENENZE_CATEGORIE TO RUOLO_MODERATOR;
GRANT SELECT ON OFFERTE_SERVIZI TO RUOLO_MODERATOR;
GRANT SELECT ON AMICIZIE TO RUOLO_MODERATOR;

-- Concediamo a tale ruolo il privilegio di CANCELLAZIONE e MODIFICA su alcune tabelle della base di dati
GRANT DELETE ON FOTOGRAFIE TO RUOLO_MODERATOR;
GRANT DELETE ON SUGGERIMENTI TO RUOLO_MODERATOR;
GRANT DELETE ON CHECK_IN TO RUOLO_MODERATOR;
GRANT DELETE ON RECENSIONI TO RUOLO_MODERATOR;
GRANT UPDATE ON FOTOGRAFIE TO RUOLO_MODERATOR;
GRANT UPDATE ON SUGGERIMENTI TO RUOLO_MODERATOR;
GRANT UPDATE ON CHECK_IN TO RUOLO_MODERATOR;
GRANT UPDATE ON RECENSIONI TO RUOLO_MODERATOR;

-- Lo USER può gestire soltanto i propri contenuti.
-- Concediamo a tale ruolo il privilegio di SELEZIONE su alcune tabelle della base di dati
GRANT SELECT ON ATTIVITA_COMMERCIALI TO RUOLO_USER;
GRANT SELECT ON CATEGORIE TO RUOLO_USER;
GRANT SELECT ON SERVIZI TO RUOLO_USER;
GRANT SELECT ON FOTOGRAFIE TO RUOLO_USER;
GRANT SELECT ON UTENTI TO RUOLO_USER;
GRANT SELECT ON RECENSIONI TO RUOLO_USER;
GRANT SELECT ON CHECK_IN TO RUOLO_USER;
GRANT SELECT ON ORARI_LAVORATIVI TO RUOLO_USER;
GRANT SELECT ON SUGGERIMENTI TO RUOLO_USER;
GRANT SELECT ON AMICIZIE TO RUOLO_USER;

-- Concediamo a tale ruolo il privilegio di INSERIMENTO ed AGGIORNAMENTO su alcune tabelle della base di dati
GRANT INSERT ON FOTOGRAFIE TO RUOLO_USER;
GRANT INSERT ON SUGGERIMENTI TO RUOLO_USER;
GRANT INSERT ON RECENSIONI TO RUOLO_USER;
GRANT INSERT ON CHECK_IN TO RUOLO_USER;
GRANT INSERT ON AMICIZIE TO RUOLO_USER;

-- Creazione di un utente ADMIN
CREATE USER Admin_della_Piattaforma IDENTIFIED BY adm;
GRANT CREATE SESSION TO Admin_della_Piattaforma;
GRANT RUOLO_ADMIN TO Admin_della_Piattaforma; 
 
-- Creazione di un utente MODERATOR
CREATE USER Moderatore_della_Piattaforma IDENTIFIED BY modrt;
GRANT CREATE SESSION TO Moderatore_della_Piattaforma;
GRANT RUOLO_MODERATOR TO Moderatore_della_Piattaforma;

-- Creazione di un utente USER
CREATE USER User_della_Piattaforma IDENTIFIED BY usr;
GRANT CREATE SESSION TO User_della_Piattaforma;
GRANT RUOLO_USER TO User_della_Piattaforma ;
